### ISSUE TITLE
RGB to YUV420 mistake

### ISSUE THREAD

**Issue by EthanVanderHorn** [secile/OpenH264Lib.NET#18]
When converting from RGB to YUV420 the U and V equations are flipped which results in a non-standard file where U and V are flipped. I discovered this when debugging and using a third party YUV to RGB converter. 

You can tell that they are flipped because V is supposed to be the red component and U the blue component but reading the equations you can see that they are not.

This error is hidden on line 58 of Decoder.cpp when the U and V are flipped again.
`byte* rgb = YUV420PtoRGB(y_plane, v_plane, u_plane, width, height, stride);`
The u_plane and v_plane arguments are in the reverse order from the function header
`byte* Decoder::YUV420PtoRGB(byte* yplane, byte* uplane, byte* vplane, int width, int height, int stride)`

The planes are also flipped in the diagram in the documentation of Decoder::YUV420PtoRGB.

**Comment by secile** [comment]
Hello, thank you for your information.

I noticed this problem when I first made this library.
In line 58 of Decoder.cpp, there is a comment 'なぜかuvが逆' (in Japanese)
that means 'I don't know why, but it works if U and V are reversed.'
I thought something wrong, but it's working fine, so I left it as it is.

This time, I investigated the reason. and I found that some little problem makes this issue.

When I encoded PNG images of blue(RGB=0000FF) to h264 movie file, blue element of movie file became RGB=113EFF.
Similarly, I encoded red(RGB=FF0000), then became RGB=CD0000. It is strange. Color is almost same, but the color has changed a little.

|  before encode(PNG)  |  after encode(h264)  |
| ---- | ---- |
|  RGB=0000FF<br><img width="150" alt="before" src="https://user-images.githubusercontent.com/29785639/122489528-dcf98800-d01a-11eb-9383-d831bf5d56f8.png"> |  RGB=113EFF<br><img width="150" alt="after" src="https://user-images.githubusercontent.com/29785639/122489582-f69acf80-d01a-11eb-82aa-74691870a9a2.png">  |
|  RGB=FF0000<br><img width="150" alt="before" src="https://user-images.githubusercontent.com/29785639/122489760-5e511a80-d01b-11eb-8621-c9eb4b6ccab7.png">  |  RGB=CD0000<br><img width="150" alt="after" src="https://user-images.githubusercontent.com/29785639/122489778-63ae6500-d01b-11eb-8b44-3392f111a2dd.png">  |

I found some problems.
- In C#, pixel order of Bitmap is 'BGR', but my code assumed that pixel order is 'RGB'.
- Since element 'B' and 'R' is swapped, V plane and U plane is swapped.
- Since B-V conversion formula is different from R-U, the color has changed.

I fixed these problems, and test again. I think color changing problem is solved.

|  before encode(PNG)  |  after encode(h264)  |
| ---- | ---- |
|  RGB=0000FF<br><img width="150" alt="before" src="https://user-images.githubusercontent.com/29785639/122489528-dcf98800-d01a-11eb-9383-d831bf5d56f8.png"> |  RGB=0000FC<br><img width="150" alt="blue_fixed" src="https://user-images.githubusercontent.com/29785639/122507270-dd098000-d03a-11eb-9150-890e4525184b.png">  |
|  RGB=FF0000<br><img width="150" alt="before" src="https://user-images.githubusercontent.com/29785639/122489760-5e511a80-d01b-11eb-8621-c9eb4b6ccab7.png">  |  RGB=FD0001<br><img width="150" alt="red_fixed" src="https://user-images.githubusercontent.com/29785639/122507283-e266ca80-d03a-11eb-9a57-5a370f55b706.png">  |

I'm currently working on a fix for this issue. After that, I will update my repository.
If you have any comment please let me know.

Thank you.
